apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: yaml-lint
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Code Quality
    tekton.dev/tags: linter
    tekton.dev/displayName: "YAML linter"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task can be used to perform lint check on YAML files
  workspaces:
    - name: supplychain-workspace
      description: A workspace that contains the fetched git repository.
  params:
    - name: args
      type: array
      description: extra args needs to append
      default: ["--help"]
  steps:
    - name: what-do-we-jave
      image: registry.harbor.learn.tapsme.org/tap/tap-packages@sha256:f325a8d83abd2f1a7741045472ab96e6929f52fd330e432777e54f8e6f459c7e
      workingDir: $(workspaces.supplychain-workspace.path)
      script: |
        #!/usr/bin/env bash
        pwd
        ls -al      
    - name: lint-yaml-files
      image: docker.io/cytopia/yamllint:1.23@sha256:e9deea51bbdc35950cacf6594dab94100d9bbf5c987540b8874167d58e6bdce2 #tag: 1.23
      workingDir: $(workspaces.supplychain-workspace.path)
      command:
        - yamllint
      args:
        - $(params.args)